### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by FishyFishsEatingFishs** [ChrisFirerabbit/Valorant-Aim-and-Navigation-Bot#1]
where do i find my host-ip and the Client ip and the client port and host port also would something like this board work? 

https://www.aliexpress.com/item/32887046460.html?spm=a2g0o.search0304.0.0.2bb82e8dYJ09Kc&algo_pvid=1c5779f2-f4f5-4680-b49b-759fb49ead27&aem_p4p_detail=202107220136121484340010602750001150456&algo_exp_id=1c5779f2-f4f5-4680-b49b-759fb49ead27-1

**Comment by FishyFishsEatingFishs** [comment]
Also im confused you say:


PC 1
├── valkyrie.py
└── valkset.json
PC 2 (Running Valorant)
├── mouseHost.py
├── Arduino For Mouse Emulation
└── Arduino For Keyboard Emulation

But then you say:

Run on machine running Valorant

./valkyrie.py
Run on machine hosting mouse inputs

./hostHouse.py


You say to run valkyrie.py on the same machine running valorant then you say to run it on the other machine

**Comment by CodeRabbyte** [comment]
1) use ipconfig cmd per machine and use any open ports
2) Probably would work, I used two arduino nanos
3) Diagram has been corrected to clear confusion, please check again.

**Comment by FishyFishsEatingFishs** [comment]
Thanks <3

**Comment by FishyFishsEatingFishs** [comment]
Ill buy 2 of those china arduinos and test it out is it possible to only use 1?

**Comment by CodeRabbyte** [comment]
Ran into issues when using one arduino to emulate both mouse and keyboard.  Your mileage may vary.

**Comment by FishyFishsEatingFishs** [comment]
Do i need to emulate the keybaord? i will only be using the aimbot
