### ISSUE TITLE
Effectiveness of Bot

### ISSUE THREAD

**Issue by ImJustUser** [ChrisFirerabbit/Valorant-Aim-and-Navigation-Bot#4]
Would you happen to have a demonstration video? I've been tinkering with this for the past hour or so and it seems painfully ineffective. I'm in the range with bots and the aimbot seems extremely slow and inaccurate. I've edited per your instructions, but i'm not sure if i've done something wrong. Have you tested this with live people? As with just the bots moving it seems impossible to hit. 

If you do not have a video, i'd be happy to upload what it looks like for me.

Thanks!

**Comment by CodeRabbyte** [comment]
Since this is meant to be educational, I have modified line(s) of code to purposeful slow down the program to reduce abuse.
